(()=>{
 const $=s=>document.querySelector(s);let mode='login',syncBusy=false,syncTimer=null,available=false;
 async function api(route,options={}){let res=await fetch(route,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let body=await res.json().catch(()=>({}));if(!res.ok){let e=new Error(body.error||`Request failed (${res.status})`);e.status=res.status;throw e}return body}
 function setSync(text,connected){let el=$('#sync-indicator');if(!el)return;el.textContent=text;el.classList.toggle('connected',!!connected);el.title=connected?'Encrypted-in-transit account sync is active.':'Progress is currently saved on this device.'}
 function show(){const user=window.Fieldnotes?.user;$('#account-label').textContent=user?user.email:available?'Sign in':'Local data';$('#account-overlay').hidden=false;$('#signout-button').hidden=!user;if(user){$('#account-form').hidden=true;$('#account-body h2').innerHTML='Your practice<br><span>is in sync.</span>';$('#account-body>p').textContent=`Signed in as ${user.email}. Your saved work syncs to your account.`;$('#account-body .account-tabs').hidden=true;$('#account-error').textContent=window.Fieldnotes.coachConfigured?'AI research coaching is configured.':'AI research coaching is off until a provider is set on this server.'}else if(!available){$('#account-form').hidden=true;$('#account-body h2').innerHTML='Your progress<br><span>stays on this device.</span>';$('#account-body>p').textContent='This public learning site keeps practice progress in this browser only.';$('#account-body .account-tabs').hidden=true;$('#account-body .account-trust').textContent='No account is required. Clearing this browser’s site data erases saved progress.';$('#account-error').textContent=''}else{$('#account-form').hidden=false;$('#account-body h2').innerHTML='Keep your practice<br><span>in sync.</span>';$('#account-body>p').textContent='Sign in to back up lessons, assessments, projects, and notes across your devices.';$('#account-body .account-tabs').hidden=false;$('#account-error').textContent=''}}
 function setMode(next){mode=next;document.querySelectorAll('[data-auth-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.authMode===mode));let name=$('[name="name"]'),password=$('[name="password"]'),submit=$('#account-submit');name.hidden=mode!=='register';name.required=mode==='register';password.autocomplete=mode==='register'?'new-password':'current-password';submit.innerHTML=(mode==='register'?'Create account':'Sign in securely')+' <span>↗</span>';$('#account-error').textContent=''}
 function emailKey(email){return'fieldnotes-state:'+email.toLowerCase()}
 function mergeForNew(local,server){let a=local||{},b=server||{};return{...b,...a,done:[...new Set([...(b.done||[]),...(a.done||[])])],goal:a.goal||b.goal,attempts:{...b.attempts,...a.attempts},skills:{...b.skills,...a.skills},projects:{...b.projects,...a.projects},reviews:{...b.reviews,...a.reviews},curriculumVersion:2}}
 async function handleSubmit(e){e.preventDefault();let form=e.currentTarget,data=Object.fromEntries(new FormData(form).entries()),btn=$('#account-submit'),err=$('#account-error'),submittedMode=mode;btn.disabled=true;btn.textContent=submittedMode==='register'?'Creating private account…':'Signing in…';err.textContent='';try{if(!available)throw new Error('The Fieldnotes server is not running. Start it with node server.mjs to create an account and sync progress.');let local=window.Fieldnotes.getState(),result=await api(submittedMode==='register'?'/api/auth/register':'/api/auth/login',{method:'POST',body:JSON.stringify(data)});let selected=result.isNew?mergeForNew(local,result.progress):result.progress;window.Fieldnotes.setAccount(result.user,selected,result.coachConfigured);localStorage.setItem(emailKey(result.user.email),JSON.stringify(selected));$('#account-overlay').hidden=true;setSync('SYNCED',true);window.Fieldnotes.toast(result.isNew?'Account created · your learning is backed up.':'Welcome back · your progress is synced.')}catch(error){err.textContent=error.message}finally{btn.disabled=false;btn.innerHTML=(submittedMode==='register'?'Create account':'Sign in securely')+' <span>↗</span>'}}
 async function loadExistingSession(){try{let me=await api('/api/me');available=true;window.Fieldnotes.setAccount(me.user,me.progress,me.coachConfigured);setSync('SYNCED',true)}catch(e){if(e.status===401){setSync('DEVICE ONLY',false);return}setSync('DEVICE ONLY',false)}}
 let pendingSync=null;async function sync(detail){if(!available||!detail?.account)return;clearTimeout(syncTimer);if(syncBusy){pendingSync=detail;return}syncTimer=setTimeout(async()=>{syncBusy=true;setSync('SYNCING…',true);try{let result=await api('/api/progress',{method:'PUT',body:JSON.stringify(detail.state)});Object.assign(detail.state,result.progress);localStorage.setItem(emailKey(detail.account.email),JSON.stringify(result.progress));setSync('SYNCED',true)}catch(e){setSync(e.status===401?'SIGN IN TO SYNC':'SYNC PAUSED',false);if(e.status===401)window.Fieldnotes.setAccount(null,null,false)}finally{syncBusy=false;if(pendingSync){let latest=pendingSync;pendingSync=null;sync(latest)}}},350)}
 async function signOut(){try{if(available)await api('/api/auth/logout',{method:'POST',body:'{}'})}catch{}window.Fieldnotes.setAccount(null,null,false);$('#account-overlay').hidden=true;setSync('DEVICE ONLY',false);window.Fieldnotes.toast('Signed out · this device is ready for local practice.')}
 async function init(){try{let info=await api('/api/health');available=!!info.ok;window.Fieldnotes.coachConfigured=!!info.coachConfigured;setSync('DEVICE ONLY',false)}catch{available=false;window.Fieldnotes.coachConfigured=false;setSync('LOCAL ONLY',false)}$('#account-open').addEventListener('click',show);document.querySelectorAll('[data-close-account]').forEach(b=>b.addEventListener('click',()=>$('#account-overlay').hidden=true));document.querySelectorAll('[data-auth-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.authMode)));$('#account-form').addEventListener('submit',handleSubmit);$('#signout-button').addEventListener('click',signOut);window.addEventListener('fieldnotes:progress-saved',e=>sync(e.detail));await loadExistingSession()}
 window.FieldnotesAuth={api,show,signOut,get available(){return available}};init();
})();
