/* The second half of the curriculum. Lesson IDs remain stable so saved work survives upgrades. */
window.ADVANCED_MODULES = [
 {title:'Python for research engineering',description:'Clean functions · NumPy and pandas · tests · reusable research',icon:'05',lessons:[
  {title:'Turn notebooks into small functions',topic:'Python engineering · functions',lang:'Python',mins:25,lead:'Move repeated calculations into small functions with explicit inputs and outputs.',body:'Keep functions focused: parse one input, validate a rule, or compute one metric. Avoid hidden global state. Separate data loading from analysis so a result can be reproduced on another dataset.',code:'def simple_returns(prices):\n    if len(prices) < 2:\n        return []\n    return [(b / a) - 1 for a, b in zip(prices, prices[1:])]\n\nprices = [100.0, 101.0, 99.99]\nprint(simple_returns(prices))',callout:'The function makes a clear contract: prices in, adjacent simple returns out. It does not yet validate timestamps, corporate actions, or zero prices.',quiz:'What makes a research function easier to reuse?',answers:['It reads hidden variables from many places.','It has a clear input/output contract and limited responsibility.','It combines loading, cleaning, modeling, and reporting in one block.'],correct:1,ex:'Small functions with explicit contracts can be tested, reused, and reviewed.'},
  {title:'Use arrays without losing the question',topic:'Python engineering · numerical computing',lang:'Python',mins:30,lead:'Vectorized calculations are concise, but shape and alignment are part of correctness.',body:'NumPy arrays support efficient elementwise operations. Before combining two arrays, establish that their indices refer to the same observations. In a real notebook, install/import NumPy and assert shapes before elementwise calculations.',code:'prices = [100.0, 101.0, 99.99, 102.0]\nreturns = [(b / a) - 1 for a, b in zip(prices, prices[1:])]\n\nprint("n prices:", len(prices))\nprint("n returns:", len(returns))\nprint("returns:", returns)',callout:'In production analysis, do not silently assume two arrays have matching dates just because their lengths match.',quiz:'Two arrays both have 100 values. What should you verify before combining them?',answers:['That they represent the same dates, units, and order.','Only that Python accepts the addition.','That both are positive.'],correct:0,ex:'Matching lengths do not guarantee that observations align in time, units, or meaning.'},
  {title:'Work with tidy tabular data',topic:'Python engineering · pandas',lang:'Python',mins:30,lead:'A tidy table gives each observation a clear row and each variable a clear column.',body:'With pandas, inspect dtypes, index, null counts, and date range before transforming data. Prefer explicit column selection, stable sorting, and validated joins. Keep a raw copy and make cleaning decisions reproducible.',code:'rows = [\n    {"symbol": "ALFA", "date": "2026-09-28", "close": 50.12},\n    {"symbol": "ALFA", "date": "2026-09-29", "close": 50.10},\n]\n\nprint("rows:", len(rows))\nprint("fields:", sorted(rows[0].keys()))\nprint("symbols:", sorted({r["symbol"] for r in rows}))',callout:'These records are synthetic. For market data, also check timezone, exchange calendar, split/dividend adjustment, duplicate keys, and survivorship effects.',quiz:'Why inspect dtypes and indexes before analysis?',answers:['They can reveal parsing and alignment errors early.','They guarantee there is no look-ahead bias.','They increase the number of observations.'],correct:0,ex:'Inspection can catch issues such as strings parsed as dates or a misaligned index.'},
  {title:'Test assumptions with assertions',topic:'Python engineering · testing',lang:'Python',mins:25,lead:'Tests check whether a calculation obeys a stated contract for chosen examples.',body:'Test ordinary cases, boundary cases, and invalid inputs. A passing test covers its case only; it does not validate your market assumptions or the quality of your data.',code:'def net_return(gross, costs):\n    return gross - costs\n\nassert net_return(0.02, 0.005) == 0.015\nassert net_return(0.001, 0.002) < 0\nprint("Example checks passed")',callout:'Keep tests next to the method they check. A research note should also explain assumptions that cannot be established by unit tests.',quiz:'A return function passes two example tests. What is established?',answers:['The trading strategy will remain profitable.','Those tested examples match the specified behavior.','The input data is unbiased.'],correct:1,ex:'Tests support confidence in specified behavior for tested cases, not the validity of the whole research design.'}]},
 {title:'Algorithms and data structures',description:'Asymptotic reasoning · maps and sets · search · coding fluency',icon:'06',lessons:[
  {title:'Estimate work before it gets expensive',topic:'Algorithms · complexity',lang:'Python',mins:25,lead:'Reason about how work scales with the size of the input, not only how fast one run feels.',body:'Big O describes an asymptotic upper bound. A pass through n values is O(n); comparing all pairs is O(n²). Constants matter in practice, but growth rate matters when datasets or event streams expand.',code:'values = [3, 1, 4, 1, 5, 9]\n# One pass: O(n)\nbest = values[0]\nfor value in values:\n    best = max(best, value)\nprint("max:", best)',callout:'Complexity analysis is a model. Measure the actual bottleneck after choosing a sound algorithm.',quiz:'Doubling n turns an O(n²) pairwise routine into approximately how many times the work?',answers:['2×','4×','n×'],correct:1,ex:'Quadratic work grows with n squared: doubling n gives roughly four times as many pair comparisons.'},
  {title:'Choose a structure for fast lookup',topic:'Algorithms · hash maps and sets',lang:'Python',mins:25,lead:'A suitable data structure can simplify logic and reduce repeated work.',body:'A Python set or dict offers average-case O(1) membership or key lookup. Use a set to detect duplicates; use a dict for mapping an identifier to metadata. Preserve ordering explicitly where sequence is part of the question.',code:'symbols = ["ALFA", "BETA", "ALFA", "GAMMA"]\nseen = set()\nduplicates = []\nfor symbol in symbols:\n    if symbol in seen:\n        duplicates.append(symbol)\n    seen.add(symbol)\nprint(duplicates)',callout:'Hash lookup is average-case; hash tables have memory costs and worst cases. Pick the structure that preserves the semantics you need.',quiz:'You need to detect whether each event ID has appeared before. A useful structure is:',answers:['A set of seen IDs.','A sorted list scanned from the beginning every time.','A floating-point array.'],correct:0,ex:'A set expresses unique membership checks directly and usually does so in average O(1) time.'},
  {title:'Use binary search only with its invariant',topic:'Algorithms · search',lang:'Python',mins:30,lead:'Binary search is fast because a sorted input lets you discard half the search interval each step.',body:'The key invariant is that if the target exists, it remains in the current inclusive or half-open interval. Specify bounds carefully; off-by-one bugs often break termination or skip a boundary.',code:'def contains(sorted_values, target):\n    lo, hi = 0, len(sorted_values)\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if sorted_values[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid\n    return lo < len(sorted_values) and sorted_values[lo] == target\n\nprint(contains([2, 4, 8, 16], 8))',callout:'The algorithm assumes sorted input. Validate that precondition or make it part of the documented contract.',quiz:'Binary search can safely eliminate half the interval because:',answers:['The list is sorted and comparison preserves an interval invariant.','The list has an even number of values.','The target is always at the midpoint.'],correct:0,ex:'Sorted order lets each comparison rule out one half while maintaining a clear search invariant.'},
  {title:'Compare two solutions, then measure',topic:'Algorithms · interview practice',lang:'Python',mins:30,lead:'Explain a correct baseline, improve it, and discuss the tradeoff.',body:'Start with the simplest correct solution. Estimate time and space, then consider a better structure. In interviews and production, communicate constraints and edge cases before optimizing.',code:'# Is any pair equal to target_sum?\nvalues = [4, 7, 2, 9]\ntarget_sum = 11\nseen = set()\nfound = False\nfor value in values:\n    if target_sum - value in seen:\n        found = True\n        break\n    seen.add(value)\nprint(found)',callout:'This hash-set approach is O(n) average time and O(n) additional space. A sorted two-pointer approach trades sorting cost for different space use.',quiz:'What is a good first step when asked to optimize an unfamiliar algorithm?',answers:['State the behavior and constraints, then identify its cost.','Rewrite it in a lower-level language immediately.','Assume the largest input is one element.'],correct:0,ex:'First establish correctness, input scale, constraints, and bottlenecks; then choose a justified improvement.'}]},
 {title:'SQL for research data',description:'Relational model · joins · windows · time-aware aggregation',icon:'07',lessons:[
  {title:'Model observations with keys',topic:'SQL · data modeling',lang:'SQL',mins:25,lead:'A table design makes its grain and unique key explicit.',body:'A daily bar table might have one row per (symbol, trading_date). A quote table may have many rows per symbol and timestamp. State primary keys and units; validate row counts after joins to catch accidental duplication.',code:'SELECT symbol, date, close\nFROM daily_prices\nWHERE symbol = \'ALFA\'\nORDER BY date;',callout:'The example database is synthetic and small. Large research systems require partitioning, indexes, and provenance beyond a classroom query.',quiz:'What should a table grain describe?',answers:['What one row represents.','The database server brand.','The style of a chart.'],correct:0,ex:'Grain describes the entity represented by each row, which helps define keys and join behavior.'},
  {title:'Join without multiplying observations',topic:'SQL · joins and validation',lang:'SQL',mins:30,lead:'A join can silently multiply rows when the key is not unique.',body:'Before joining, check key uniqueness and expected cardinality. Use explicit join conditions and compare row counts. A many-to-many join may create plausible but incorrect totals.',code:'SELECT p.symbol, p.date, p.close, f.sector\nFROM daily_prices AS p\nJOIN fundamentals AS f\n  ON p.symbol = f.symbol\nWHERE p.date = \'2026-09-29\';',callout:'For point-in-time research, a current fundamentals row can leak future revisions. Join on an availability timestamp, not just a company key.',quiz:'A join triples your row count unexpectedly. What should you inspect?',answers:['Key uniqueness and join cardinality on both sides.','Only the chart color.','Whether SQL is case sensitive.'],correct:0,ex:'Duplicate join keys can multiply observations. Check uniqueness and the intended relationship.'},
  {title:'Aggregate by time without leakage',topic:'SQL · windows',lang:'SQL',mins:30,lead:'Window functions compute rolling and grouped values while keeping row-level observations.',body:'A window frame defines which rows contribute. A trailing average should use only current and past observations. Specify the ORDER BY and frame bounds explicitly; default frames can surprise you.',code:'SELECT symbol, date, close,\n       AVG(close) OVER (\n         PARTITION BY symbol ORDER BY date\n         ROWS BETWEEN 4 PRECEDING AND CURRENT ROW\n       ) AS trailing_mean_5\nFROM daily_prices;',callout:'In the practice dataset there are only a few synthetic records, so a five-row estimate is mostly NULL or a partial window. The query illustrates semantics, not statistical power.',quiz:'A trailing feature at time t should generally use:',answers:['Only observations available at or before t.','The full sample, including future dates.','A random row order.'],correct:0,ex:'A point-in-time trailing feature must not use data from after its decision time.'},
  {title:'Make queries auditable',topic:'SQL · reproducible analysis',lang:'SQL',mins:25,lead:'A clear query exposes its filters, ordering, and aggregation decisions.',body:'Avoid SELECT * in stable analysis. Name columns, use meaningful aliases, parameterize values in application code, and record source/version and date range. Inspect a sample before trusting a summary.',code:'SELECT symbol, COUNT(*) AS row_count,\n       MIN(date) AS first_date, MAX(date) AS last_date\nFROM daily_prices\nGROUP BY symbol\nORDER BY symbol;',callout:'A query result is only as trustworthy as its source, timestamp semantics, and transformations.',quiz:'Why explicitly list columns instead of using SELECT * in a durable report?',answers:['It makes selected fields and schema dependencies visible.','It always makes the query faster.','It automatically deduplicates rows.'],correct:0,ex:'Explicit columns improve readability and help reveal schema dependencies.'}]},
 {title:'Probability for decisions',description:'Conditional probability · Bayes · expectation · risk intuition',icon:'08',lessons:[
  {title:'Work with conditional probability',topic:'Probability · conditioning',lang:'Python',mins:30,lead:'A probability is incomplete until its conditioning information is clear.',body:'P(A | B) means the chance of A under the condition B. In markets, conditioning on a signal, liquidity state, or selection rule changes the relevant sample and may change the estimated probability.',code:'events = [(True, True), (True, False), (False, True), (False, False)]\n# Illustrative Boolean pairs: (signal, up)\nsignal_cases = [up for signal, up in events if signal]\np_up_given_signal = sum(signal_cases) / len(signal_cases)\nprint(p_up_given_signal)',callout:'Tiny examples teach definitions, not reliable market probabilities. Estimation needs representative data and uncertainty analysis.',quiz:'P(up | signal) asks:',answers:['The chance of an up move among cases where the signal occurred.','The chance the signal occurs among all up moves.','The unconditional chance of any return.'],correct:0,ex:'Conditioning on the signal restricts the reference set to signal cases.'},
  {title:'Update beliefs with Bayes’ rule',topic:'Probability · Bayes',lang:'Python',mins:30,lead:'A signal’s apparent accuracy must be interpreted against the base rate.',body:'Bayes’ rule combines a prior, a likelihood, and observed evidence. A rare event can remain unlikely after a moderately informative positive test. In research, compare the base rate to the conditional behavior under a signal.',code:'prior = 0.02\nsensitivity = 0.90\nfalse_positive_rate = 0.05\npositive = sensitivity * prior + false_positive_rate * (1 - prior)\nposterior = sensitivity * prior / positive\nprint(f"P(event | positive): {posterior:.1%}")',callout:'The numbers are a teaching example, not market estimates. The denominator includes both true and false positives.',quiz:'Why does base rate matter when interpreting a signal?',answers:['Because evidence updates prior odds; it does not erase them.','Because rare events are impossible.','Because the false-positive rate is irrelevant.'],correct:0,ex:'Posterior probability depends on both the prior event rate and the signal likelihoods.'},
  {title:'Compute expectation with a tree',topic:'Probability · expected value',lang:'Python',mins:25,lead:'Expected value weights possible outcomes by their probabilities.',body:'E[X] is a probability-weighted average. It does not describe dispersion or guarantee a typical outcome. For a trading decision, include payoff shape, costs, sizing, and uncertainty in estimated probabilities.',code:'outcomes = [(-1.0, 0.6), (2.0, 0.4)]\nexpected = sum(value * probability for value, probability in outcomes)\nprint("Expected units:", expected)',callout:'A positive estimated expectation is not enough: estimation error, tail risk, capital limits, and implementation costs matter.',quiz:'An expectation of +0.2 units means:',answers:['Every trial earns exactly 0.2 units.','The probability-weighted average is 0.2 units under the stated model.','The model is certainly correct.'],correct:1,ex:'Expected value is an average under the assumed distribution, not a guarantee about any one realization.'},
  {title:'Use simulation to test intuition',topic:'Probability · Monte Carlo',lang:'Python',mins:30,lead:'Simulation can make a probabilistic model tangible and expose variance around outcomes.',body:'Monte Carlo simulation samples from a specified model. It does not validate that the model describes reality. Set a seed for reproducibility; compare simulated quantities with an analytic answer when possible.',code:'import random\nrandom.seed(7)\nn = 10000\nheads = sum(random.random() < 0.5 for _ in range(n))\nprint("Estimated P(heads):", heads / n)',callout:'Simulation error shrinks slowly—roughly with the square root of sample size. More draws do not fix an unrealistic model.',quiz:'What does a large number of simulated draws improve?',answers:['Monte Carlo precision under the chosen model.','The truth of the chosen model.','The quality of undocumented data.'],correct:0,ex:'More simulation reduces Monte Carlo noise but cannot validate the assumptions being simulated.'}]},
 {title:'Statistics and experimental design',description:'Estimators · uncertainty · multiple tests · causal caution',icon:'09',lessons:[
  {title:'Distinguish estimates from truth',topic:'Statistics · sampling',lang:'Python',mins:30,lead:'An observed average is an estimate from a sample, not a known population parameter.',body:'Samples vary. Standard errors describe estimator variability under assumptions. Dependence, heavy tails, changing regimes, and selection can make textbook formulas unreliable; choose methods that fit the data-generating process.',code:'returns = [0.01, -0.02, 0.015, 0.005, -0.003]\nmean = sum(returns) / len(returns)\nprint("sample size:", len(returns))\nprint("sample mean:", mean)',callout:'Always report sample size, dates, sampling scheme, and a measure of uncertainty appropriate to dependence and tails.',quiz:'An estimated mean differs across two samples. This can happen because:',answers:['Samples have natural sampling variation.','One sample must be fraudulent.','The true mean changes every time you calculate it.'],correct:0,ex:'Different samples from the same population can yield different estimates.'},
  {title:'Read uncertainty intervals carefully',topic:'Statistics · confidence intervals',lang:'Python',mins:30,lead:'An interval summarizes uncertainty under a procedure and its assumptions.',body:'A frequentist 95% confidence procedure has a long-run coverage interpretation under stated conditions. It is not a 95% probability that a fixed parameter lies in this specific computed interval. In small, dependent return samples, naive intervals can mislead.',code:'import math\nvalues = [0.01, -0.02, 0.015, 0.005, -0.003]\nn = len(values)\nmean = sum(values) / n\nvariance = sum((x - mean) ** 2 for x in values) / (n - 1)\nse = math.sqrt(variance / n)\nprint("mean:", mean, "SE:", se)',callout:'This plug-in standard error assumes independent observations and a well-behaved sample. Those assumptions often need adjustment for financial time series.',quiz:'A confidence interval’s coverage claim depends on:',answers:['Its sampling procedure and assumptions.','The analyst’s confidence.','Whether its endpoints look symmetrical.'],correct:0,ex:'Coverage is a property of a procedure under assumptions, not a guarantee about one interval.'},
  {title:'Recognize multiple testing',topic:'Statistics · selection bias',lang:'Python',mins:30,lead:'Trying many variants and reporting the best one makes a lucky result likely.',body:'The more hypotheses examined, the more likely an extreme result appears by chance. Record all trials, reserve untouched evaluation data, and treat data snooping as part of the design—not a footnote.',code:'trials = 1000\nalpha = 0.05\nchance_at_least_one = 1 - (1 - alpha) ** trials\nprint(f"Illustrative chance: {chance_at_least_one:.1%}")',callout:'This assumes independent tests under a null—real strategy variants are correlated. The calculation illustrates multiplicity, not the exact risk in a research pipeline.',quiz:'Why does reporting only the best of many strategies bias the evidence?',answers:['Selection favors extreme outcomes, including lucky noise.','The best strategy always has lower fees.','Multiple testing changes the historical prices.'],correct:0,ex:'Selecting the strongest observed result creates a winner’s curse.'},
  {title:'Design a credible comparison',topic:'Statistics · experiments',lang:'Python',mins:30,lead:'A credible experiment defines comparisons before outcomes are known.',body:'Specify the hypothesis, universe, sampling, benchmark, metrics, exclusions, and stopping rule. For time series, random shuffling can leak temporal structure; use chronological splits and uncertainty methods that respect dependence.',code:'dates = list(range(100))\ncut = 70\ntrain = dates[:cut]\nvalidation = dates[cut:85]\ntest = dates[85:]\nprint(len(train), len(validation), len(test))',callout:'A chronological split helps prevent future observations from informing earlier decisions, but careful feature availability checks are still needed.',quiz:'Why prefer chronological splits for predictive time-series work?',answers:['They better match the information order of a live decision.','They guarantee independent samples.','They maximize training size in every case.'],correct:0,ex:'A chronological evaluation more closely respects what information would have been available at each time.'}]},
 {title:'Linear algebra and optimization',description:'Vectors · covariance · least squares · constrained decisions',icon:'10',lessons:[
  {title:'Think in vectors and dimensions',topic:'Linear algebra · vectors',lang:'Python',mins:25,lead:'Represent aligned observations as vectors and check dimensions before applying a formula.',body:'A vector can represent returns across assets or features for one observation. A matrix can represent many aligned samples. Units and ordering matter as much as shape; a dimensionally valid expression can still be conceptually wrong.',code:'weights = [0.60, 0.40]\nasset_returns = [0.01, -0.005]\nportfolio_return = sum(w * r for w, r in zip(weights, asset_returns))\nprint(portfolio_return)',callout:'Weights must correspond to the same assets and time as the returns. Check ordering and whether weights sum to the intended exposure.',quiz:'For a portfolio dot product, what must align?',answers:['Each weight with the return for the same asset and period.','Only the decimal precision.','The names of the Python variables.'],correct:0,ex:'A dot product is meaningful only when matching elements refer to corresponding variables.'},
  {title:'Understand covariance and diversification',topic:'Linear algebra · covariance',lang:'Python',mins:30,lead:'Portfolio variance depends on both individual variances and cross-asset covariance.',body:'Diversification depends on co-movement, not just the number of holdings. Covariance estimates are noisy and regime-dependent. Correlation normalizes covariance but does not imply causation or stability.',code:'returns_a = [0.02, -0.01, 0.01, 0.00]\nreturns_b = [0.01, -0.005, 0.008, 0.002]\nmean_a = sum(returns_a) / len(returns_a)\nmean_b = sum(returns_b) / len(returns_b)\ncov_num = sum((a-mean_a)*(b-mean_b) for a,b in zip(returns_a, returns_b))\nprint("sample covariance:", cov_num / (len(returns_a)-1))',callout:'A tiny covariance sample is not a dependable risk model. Inspect stability, shrinkage choices, and stress behavior.',quiz:'Two assets with low individual volatility can still create a risky portfolio if:',answers:['Their returns co-move strongly in the same direction.','Their names are similar.','They trade on different weekdays.'],correct:0,ex:'Portfolio risk includes covariance terms between holdings.'},
  {title:'Interpret least squares',topic:'Optimization · regression',lang:'Python',mins:30,lead:'Least squares chooses parameters that minimize squared residuals under a specified design.',body:'Regression can describe conditional association, but its interpretation depends on the design, feature timing, omitted variables, and error structure. Check residuals and compare against a simple baseline.',code:'x = [1, 2, 3, 4]\ny = [2, 3, 5, 4]\nxbar, ybar = sum(x)/len(x), sum(y)/len(y)\nbeta = sum((a-xbar)*(b-ybar) for a,b in zip(x,y)) / sum((a-xbar)**2 for a in x)\nalpha = ybar - beta*xbar\nprint("alpha:", alpha, "beta:", beta)',callout:'This compact calculation is an illustration, not a statistical library. Validate model assumptions and point-in-time features before drawing conclusions.',quiz:'A fitted regression coefficient alone establishes:',answers:['An association under the fitted sample and specification.','A causal mechanism.','A stable prediction in future regimes.'],correct:0,ex:'A coefficient is conditional on the data and model; causality or stability requires further design and evidence.'},
  {title:'Add constraints to an optimization problem',topic:'Optimization · constraints',lang:'Python',mins:30,lead:'An optimizer will exploit whatever objective and constraints you give it—including mistakes.',body:'Portfolio construction often imposes bounds, leverage limits, turnover costs, and liquidity constraints. If expected returns or covariance are noisy, an unconstrained optimizer can amplify estimation error.',code:'target_weights = [0.8, 0.5]\nmax_abs_weight = 0.6\nweights = [max(-max_abs_weight, min(max_abs_weight, w)) for w in target_weights]\nprint(weights, "gross exposure:", sum(abs(w) for w in weights))',callout:'Clipping one vector is not a full optimizer. Make all constraints, objective terms, and infeasibility behavior explicit.',quiz:'Why constrain an optimizer using practical exposure and turnover limits?',answers:['To reduce implausible solutions and reflect implementation limits.','To make noisy expected returns perfectly accurate.','To ensure the objective is positive.'],correct:0,ex:'Constraints can prevent mathematical optima that are operationally or risk-wise unacceptable.'}]},
 {title:'Time series and econometrics',description:'Autocorrelation · stationarity · volatility · point-in-time validation',icon:'11',lessons:[
  {title:'Respect order and dependence',topic:'Time series · autocorrelation',lang:'Python',mins:25,lead:'Financial observations arrive in time; adjacent values may not be independent.',body:'Autocorrelation measures linear dependence across lags. Overlapping horizons, volatility clustering, and market structure can invalidate independent-sample shortcuts. Preserve timestamps in preprocessing and evaluation.',code:'returns = [0.01, -0.02, 0.015, 0.005, -0.003]\nlag1_pairs = list(zip(returns[:-1], returns[1:]))\nprint("adjacent pairs:", lag1_pairs)',callout:'Inspect serial dependence and justify uncertainty methods. Do not shuffle temporal observations casually.',quiz:'Why can a random train/test split mislead for time series?',answers:['It can let future regimes or information influence the training evaluation.','It creates missing columns.','It converts floats to integers.'],correct:0,ex:'Random splitting can break time order and make the evaluation unlike a real forecast.'},
  {title:'Question stationarity before forecasting',topic:'Time series · stationarity',lang:'Python',mins:30,lead:'A stable-looking mean or variance in one window may not persist in another.',body:'Stationarity assumptions enable many time-series tools, but structural breaks and regime shifts are common. Plot and summarize rolling behavior; compare windows; choose models that tolerate changes where appropriate.',code:'series = [1.0, 1.1, 0.9, 1.2, 2.2, 2.0, 2.4, 2.1]\nwindow = 4\nfor i in range(len(series)-window+1):\n    chunk = series[i:i+window]\n    print(i, round(sum(chunk)/window, 3))',callout:'Rolling means are descriptive diagnostics, not a formal proof of stationarity.',quiz:'A process is weakly stationary when, broadly, its mean and covariance structure:',answers:['Do not change with calendar time.','Always trend upward.','Are estimated from one observation.'],correct:0,ex:'Weak stationarity concerns time-invariant mean and autocovariance under the definition used.'},
  {title:'Separate signal from volatility clustering',topic:'Time series · volatility',lang:'Python',mins:30,lead:'Return direction and return magnitude can have different dependence patterns.',body:'Returns may show weak linear autocorrelation while absolute or squared returns show persistence. This motivates volatility models and volatility-aware risk estimates. It does not itself imply a tradable directional signal.',code:'returns = [0.01, -0.02, 0.015, -0.03, 0.004]\nabs_returns = [abs(r) for r in returns]\nsquared = [r*r for r in returns]\nprint("absolute moves:", abs_returns)\nprint("squared moves:", squared)',callout:'Volatility forecasting can support risk control without forecasting return direction.',quiz:'Persistent volatility most directly describes persistence in:',answers:['The magnitude of returns.','The sign of every next return.','The exchange name.'],correct:0,ex:'Volatility clustering concerns magnitudes or conditional variance rather than guaranteed return signs.'},
  {title:'Evaluate forecasts chronologically',topic:'Time series · walk-forward',lang:'Python',mins:30,lead:'Walk-forward evaluation repeatedly trains on the past and evaluates on later observations.',body:'Choose retraining cadence, horizon, feature availability, and metrics before evaluating. Prevent overlap or leakage between labels and folds. Report variability across periods rather than only the aggregate.',code:'folds = [(0, 50, 50, 60), (0, 60, 60, 70), (0, 70, 70, 80)]\nfor train_start, train_end, test_start, test_end in folds:\n    print(f"train [{train_start},{train_end}) test [{test_start},{test_end})")',callout:'Chronological folds reduce one kind of leakage; they do not remove model-selection bias if you repeatedly tune to the folds.',quiz:'What is a walk-forward test intended to mimic?',answers:['Repeatedly using past data to make decisions on future data.','Randomly permuting the market.','Selecting a model after seeing every test label.'],correct:0,ex:'Walk-forward evaluation simulates chronological model development and subsequent decisions.'}]},
 {title:'Market microstructure and execution',description:'Order books · auctions · impact · inventory and adverse selection',icon:'12',lessons:[
  {title:'Read a limit order book',topic:'Microstructure · order book',lang:'Python',mins:25,lead:'A quote is an offer to trade under specified conditions—not a promise that your order will fill.',body:'The bid and ask, displayed depth, queue priority, venue rules, and cancellations all shape execution. Mid-price is a reference mark, not necessarily an executable price.',code:'bid = 50.08\nask = 50.14\nmid = (bid + ask) / 2\nhalf_spread = (ask - bid) / 2\nprint("mid:", mid, "half-spread:", half_spread)',callout:'A top-of-book snapshot misses queue position, hidden liquidity, latency, and subsequent order flow.',quiz:'Why is the mid-price not necessarily an executable price?',answers:['It is between quotes; trading may require crossing the spread or waiting in a queue.','It always includes your market impact.','It is defined as the last fill.'],correct:0,ex:'The midpoint is a reference price between bid and ask; fills depend on available orders and execution choices.'},
  {title:'Model spread, fees, and impact separately',topic:'Microstructure · execution costs',lang:'Python',mins:30,lead:'Different execution costs have different drivers; one fixed haircut can conceal important risk.',body:'Spread cost depends on side and aggressiveness. Fees depend on venue and liquidity role. Market impact depends on size, liquidity, and urgency. Slippage compares expected and realized execution. Define conventions to avoid double-counting.',code:'gross_bps = 18\nspread_bps = 6\nfees_bps = 1\nimpact_bps = 3\nslippage_bps = 2\nnet_bps = gross_bps - spread_bps - fees_bps - impact_bps - slippage_bps\nprint("net bps:", net_bps)',callout:'This arithmetic is illustrative. Calibrate costs to order size, venue, time, and actual execution data.',quiz:'Why model spread, fees, slippage, and impact separately?',answers:['Their sources and scaling differ, so assumptions can be inspected.','They are interchangeable.','Separate terms guarantee low costs.'],correct:0,ex:'Disaggregated cost assumptions are easier to calibrate and stress individually.'},
  {title:'Reason about adverse selection',topic:'Microstructure · adverse selection',lang:'Python',mins:30,lead:'A fill is not random if counterparties trade when they have better information.',body:'A passive order earns spread only when filled, and fills may be more likely just before an unfavorable price move. Evaluate markouts conditional on fills and compare fill rates, spread capture, and inventory risk.',code:'fills = [100.00, 100.02, 99.98]\nfuture_marks = [99.98, 100.01, 99.95]\nmarkouts = [m - p for p, m in zip(fills, future_marks)]\nprint("markouts:", markouts)',callout:'Define the markout horizon, side convention, and fill selection. Unfilled quotes also affect the strategy’s opportunity set.',quiz:'Adverse selection means passive fills may be:',answers:['More likely when the next price move is unfavorable to the resting order.','Guaranteed at the mid-price.','Independent of incoming order flow.'],correct:0,ex:'Counterparties may choose to trade when their information makes the fill unfavorable to the resting quote.'},
  {title:'Manage inventory and auction uncertainty',topic:'Microstructure · risk scenarios',lang:'Python',mins:30,lead:'Market making and auction strategies manage uncertain fills and resulting inventory.',body:'Inventory changes exposure, hedging needs, and quote incentives. Auctions have indicative prices and imbalances that can change before the uncross. Use scenarios, position limits, and explicit invalidation—not one snapshot as certainty.',code:'inventory = 120\nprice = 50.12\nnotional = inventory * price\nlimit = 7000\nprint("notional:", notional, "within limit:", notional <= limit)',callout:'A limit is a control, not evidence of expected return. Define what happens when the limit is breached or market conditions change.',quiz:'A displayed auction imbalance should be treated as:',answers:['A time-stamped observation to test, not a guaranteed directional outcome.','A guaranteed executable price.','A complete estimate of future liquidity.'],correct:0,ex:'Displayed interest may change and does not guarantee either price direction or a fill.'}]},
 {title:'Systems, reliability, and reproducibility',description:'Linux and Git habits · performance · streaming · production controls',icon:'13',lessons:[
  {title:'Make an analysis reproducible',topic:'Systems · reproducibility',lang:'Python',mins:25,lead:'A research result should be regenerable from recorded inputs and code.',body:'Record source, retrieval time, data version, configuration, code revision, and environment. Make transformations deterministic where possible and avoid manual spreadsheet edits in the critical path.',code:'research_run = {\n    "data_version": "synthetic-v1",\n    "seed": 7,\n    "horizon": 1,\n    "cost_model": "spread+fees+impact",\n}\nfor key, value in research_run.items():\n    print(f"{key}={value}")',callout:'A real system should save immutable run metadata alongside outputs, rather than relying on a printed dictionary.',quiz:'Which metadata most helps reproduce a result?',answers:['Data/version, code revision, configuration, and environment.','The analyst’s favorite color.','Only the final Sharpe ratio.'],correct:0,ex:'Reproduction requires knowing which inputs, code, and settings generated the result.'},
  {title:'Use Git to make changes reviewable',topic:'Systems · version control',lang:'JavaScript',mins:20,lead:'Version control makes experiments and code review safer.',body:'Use small descriptive commits, branch for experiments, and review diffs before merging. Keep raw sensitive data and credentials out of repositories. A commit is a snapshot, not a complete record of data provenance.',code:'// A practical research change record\nconst change = {\n  question: "Does the feature survive costs?",\n  files: ["signal.py", "tests/test_signal.py"],\n  reason: "Add explicit one-period lag",\n};\nconsole.log(change);',callout:'Do not commit API keys or licensed datasets. Use secret storage and record permitted source identifiers.',quiz:'Why review a diff before merging research code?',answers:['To see the exact behavior and files that changed.','To guarantee the analysis is statistically valid.','To increase the number of commits.'],correct:0,ex:'A diff helps reviewers understand changes, but statistical validity still needs separate scrutiny.'},
  {title:'Measure performance before optimizing',topic:'Systems · profiling',lang:'Python',mins:25,lead:'Profile representative workloads and optimize the actual bottleneck.',body:'Big-O guides choices, but I/O, Python overhead, memory pressure, and data layout can dominate. Measure with realistic input sizes, validate correctness before and after, and avoid premature complexity.',code:'import time\nvalues = list(range(100000))\nstart = time.perf_counter()\ntotal = sum(values)\nelapsed = time.perf_counter() - start\nprint("total:", total)\nprint("seconds:", round(elapsed, 6))',callout:'Microbenchmarks can be noisy. Repeat measurements and profile the whole workflow before drawing a performance conclusion.',quiz:'Before optimizing, what should you establish?',answers:['A measured bottleneck on representative workloads.','That the code is long.','That one run was slower than expected.'],correct:0,ex:'Measurement prevents effort being spent on code that does not materially limit the system.'},
  {title:'Design for failure and controls',topic:'Systems · reliability',lang:'Python',mins:30,lead:'A useful research system makes data issues and unsafe states visible.',body:'Validate inputs, add timeouts and retries for external systems, log actionable errors, and fail closed when critical data is stale. Separate research permissions from execution permissions. Human review and operational controls matter.',code:'def validate_quote(bid, ask, timestamp_age_seconds):\n    if bid <= 0 or ask <= 0:\n        return False, "non-positive price"\n    if bid > ask:\n        return False, "crossed quote; inspect feed"\n    if timestamp_age_seconds > 5:\n        return False, "stale quote"\n    return True, "ok"\n\nprint(validate_quote(50.08, 50.14, 1))',callout:'This is a toy validation check, not a safe trading execution gate. Live systems require extensive testing, monitoring, and formal operational controls.',quiz:'If a critical market-data feed is stale, a robust automated process should:',answers:['Flag it and prevent unsafe downstream action according to defined controls.','Silently reuse an old quote forever.','Assume the price is unchanged.'],correct:0,ex:'Stale critical inputs should trigger explicit controls rather than silently propagating an unsafe value.'}]}
];

window.PRACTICE_BANK = [
 {id:'prob-base-rate',skill:'Probability',difficulty:1,type:'choice',prompt:'A fair coin is tossed twice. Given that at least one toss is heads, what is the probability both are heads?',choices:['1/4','1/3','1/2','2/3'],answer:1,explanation:'The conditioned outcomes are HH, HT, and TH. One of the three is HH.',hint:'List the equally likely outcomes remaining after applying the condition.'},
 {id:'prob-expectation',skill:'Probability',difficulty:1,type:'choice',prompt:'A game pays +3 with probability 0.25 and −1 otherwise. What is its expected payoff?',choices:['−0.5','0','0.5','1'],answer:1,explanation:'0.25 × 3 + 0.75 × (−1) = 0.75 − 0.75 = 0.',hint:'Multiply each outcome by its probability, then add.'},
 {id:'prob-bayes',skill:'Probability',difficulty:2,type:'choice',prompt:'An event occurs 1% of the time. A test has 90% sensitivity and a 5% false-positive rate. Approximately what is P(event | positive)?',choices:['1%','15%','50%','90%'],answer:1,explanation:'0.009 / (0.009 + 0.0495) ≈ 15.4%. The base rate matters.',hint:'Use Bayes: sensitivity × prior divided by total positive probability.'},
 {id:'prob-variance',skill:'Probability',difficulty:2,type:'choice',prompt:'If X and Y are independent with finite variance, Var(X + Y) is:',choices:['Var(X) + Var(Y)','Var(X) − Var(Y)','Var(X)Var(Y)','Always zero'],answer:0,explanation:'The covariance term vanishes for independent variables, so variances add.',hint:'Use Var(X+Y)=Var(X)+Var(Y)+2Cov(X,Y).'},
 {id:'stats-mean',skill:'Statistics',difficulty:1,type:'choice',prompt:'Which summary is most robust to a single extremely large observation?',choices:['Mean','Median','Variance','Maximum'],answer:1,explanation:'The median depends on rank, so one extreme value has limited effect.',hint:'Think about which statistic depends on order rather than magnitude.'},
 {id:'stats-se',skill:'Statistics',difficulty:2,type:'choice',prompt:'Under independent observations with finite variance, how does the standard error of a sample mean scale as n quadruples?',choices:['It doubles','It halves','It stays constant','It quadruples'],answer:1,explanation:'SE scales as 1/√n. Quadrupling n halves it.',hint:'Recall the square-root law for the standard error.'},
 {id:'stats-testing',skill:'Statistics',difficulty:2,type:'choice',prompt:'You test 200 independent null hypotheses at a 5% false-positive rate. About how many false positives are expected if all nulls are true?',choices:['0.1','1','10','100'],answer:2,explanation:'200 × 0.05 = 10 expected false positives.',hint:'Expected count equals number of tests times the per-test rate.'},
 {id:'stats-leakage',skill:'Statistics',difficulty:2,type:'choice',prompt:'A model uses each day’s closing price to predict that same day’s close-to-close return. The main concern is:',choices:['Look-ahead or target leakage','Too few columns','A high variance estimator only','Overly conservative fees'],answer:0,explanation:'The feature includes information from the period whose return it is meant to forecast.',hint:'Check whether the feature was available when the simulated decision was made.'},
 {id:'linear-dot',skill:'Linear algebra',difficulty:1,type:'choice',prompt:'A portfolio has weights (0.6, 0.4) and asset returns (2%, −1%). What is the portfolio return?',choices:['0.2%','0.8%','1.4%','3.0%'],answer:1,explanation:'0.6 × 2% + 0.4 × (−1%) = 0.8%.',hint:'Compute the weighted sum.'},
 {id:'linear-cov',skill:'Linear algebra',difficulty:2,type:'choice',prompt:'Two assets have equal variance σ² and correlation ρ. Covariance is:',choices:['ρσ²','σ²/ρ','ρ + σ²','Always zero'],answer:0,explanation:'Cov(X,Y)=Corr(X,Y) × SD(X) × SD(Y)=ρσ².',hint:'Correlation is covariance divided by the product of standard deviations.'},
 {id:'algo-search',skill:'Algorithms',difficulty:1,type:'choice',prompt:'Binary search on a sorted array of one million values needs on the order of:',choices:['20 comparisons','1,000 comparisons','500,000 comparisons','1,000,000 comparisons'],answer:0,explanation:'log₂(1,000,000) is about 20.',hint:'Each step halves the remaining interval.'},
 {id:'algo-hash',skill:'Algorithms',difficulty:2,type:'choice',prompt:'To find duplicates in a stream with one pass and average O(1) membership checks, use:',choices:['A set of seen keys','Nested loops over all prior values','Repeatedly sort the entire stream','A queue only'],answer:0,explanation:'A hash set records seen keys and supports average constant-time membership.',hint:'Choose a structure that answers “have I seen this key?”'},
 {id:'sql-where',skill:'SQL',difficulty:1,type:'choice',prompt:'Which clause filters individual rows before GROUP BY?',choices:['HAVING','WHERE','ORDER BY','LIMIT'],answer:1,explanation:'WHERE filters rows before grouping; HAVING filters groups after aggregation.',hint:'Distinguish row filtering from aggregate filtering.'},
 {id:'sql-join',skill:'SQL',difficulty:2,type:'choice',prompt:'A join unexpectedly multiplies rows. What do you inspect first?',choices:['Key uniqueness and join cardinality','The database logo','Column capitalization only','The chart palette'],answer:0,explanation:'Duplicate keys on either side can create one-to-many or many-to-many multiplication.',hint:'Check the grain and uniqueness of join keys.'},
 {id:'sql-window',skill:'SQL',difficulty:3,type:'choice',prompt:'A trailing five-row mean at time t should include:',choices:['Rows t−4 through t','Rows t through t+4','All observations in the dataset','A random set of five rows'],answer:0,explanation:'A trailing frame uses current and past observations only.',hint:'Maintain point-in-time availability.'},
 {id:'timeseries-split',skill:'Time series',difficulty:2,type:'choice',prompt:'Why is a chronological test split usually preferable for forecasting?',choices:['It respects the direction of information flow','It guarantees stationarity','It always creates balanced classes','It removes serial correlation'],answer:0,explanation:'Training on past and testing on future better reflects live deployment.',hint:'Consider what the model knows at decision time.'},
 {id:'timeseries-vol',skill:'Time series',difficulty:3,type:'choice',prompt:'Returns have little autocorrelation, but absolute returns are persistent. This is evidence most consistent with:',choices:['Volatility clustering','A guaranteed directional signal','No dependence of any kind','Survivorship bias only'],answer:0,explanation:'Magnitude dependence is consistent with volatility clustering, not necessarily predictable direction.',hint:'Separate dependence in sign from dependence in magnitude.'},
 {id:'micro-spread',skill:'Microstructure',difficulty:1,type:'choice',prompt:'Best bid is 100.00 and best ask is 100.06. The quoted spread is:',choices:['0.03','0.06','100.03','0.06%'],answer:1,explanation:'Spread = ask − bid = 0.06 price units.',hint:'Subtract bid from ask; the spread is not the half-spread.'},
 {id:'micro-adverse',skill:'Microstructure',difficulty:3,type:'choice',prompt:'A passive order is more likely to fill just before price moves against it. This is:',choices:['Adverse selection','A guaranteed rebate','Look-ahead bias','A market-on-close order'],answer:0,explanation:'The flow that selects your resting quote may be informed or otherwise predictive.',hint:'Ask whether fill probability is independent of future price movement.'},
 {id:'systems-tests',skill:'Systems',difficulty:1,type:'choice',prompt:'A passing unit test establishes that:',choices:['A specified example behaved as expected','The entire strategy is profitable','The source data is unbiased','The code has no bugs'],answer:0,explanation:'Tests cover specified cases; they do not prove global correctness or research validity.',hint:'State the scope of a test result.'},
 {id:'systems-repro',skill:'Systems',difficulty:2,type:'choice',prompt:'Which bundle best supports reproducing a result?',choices:['Data version, code revision, config, and environment','Only a screenshot','Only the final metric','The analyst’s memory'],answer:0,explanation:'Together these identify the inputs and implementation used for the run.',hint:'What would another researcher need to rerun the analysis?'}
];

window.RESEARCH_PROJECTS = [
 {id:'clean-data',title:'Build a point-in-time data audit',level:'Foundation · data & SQL',prereq:['1-0','1-1','1-2'],brief:'Create a documented quality report for a synthetic daily price dataset. Treat data quality as a research deliverable.',steps:['Define the table grain and intended key.','Report missing dates, duplicates, nulls, invalid prices, and volume anomalies.','Join a synthetic symbol table and demonstrate key-cardinality checks.','Write exclusions as explicit, reviewable rules.','Create a reproducible summary and a short limitations note.'],rubric:['Checks cover all stated invariants','Every exclusion is documented','Counts reconcile before and after transforms','Limitations identify what synthetic data cannot establish'],failure:'A clean-looking summary without counts and a repeatable rule is not an audit. Preserve the raw input and show each transformation.'},
 {id:'signal-lab',title:'Test one market hypothesis honestly',level:'Intermediate · research & validation',prereq:['10-0','10-1','10-2'],brief:'Form a falsifiable, point-in-time signal hypothesis and test whether any apparent effect survives realistic costs.',steps:['Write the hypothesis, mechanism, universe, time horizon, and invalidation condition before analyzing.','Validate timestamps, adjustments, missing data, and feature availability.','Build a simple baseline and chronological train/validation/holdout evaluation.','Include spread, fees, slippage, and a size-sensitive impact assumption.','Report uncertainty, drawdown, regime splits, variants tried, and a negative-result interpretation.'],rubric:['No same-period or future information leakage','Costs and fills have explicit assumptions','Holdout is untouched during design','Uncertainty and multiple testing are discussed','The result is reproducible and does not overclaim'],failure:'A positive aggregate return is not sufficient. Compare to a baseline, inspect failed periods, stress costs, and report when evidence is weak.'},
 {id:'auction-study',title:'Study an opening-auction signal',level:'Advanced · execution research',prereq:['10-1','10-2'],brief:'Evaluate whether an indicative auction imbalance contains stable, executable information after fill selection and costs.',steps:['Define the imbalance timestamp and decision cutoff.','Compare conditional and unconditional post-auction outcomes by period and liquidity bucket.','Model the indicative-price changes, fill probability, partial fills, and adverse selection.','Use chronological holdouts and test robustness to threshold choice.','Write an execution-aware decision memo with failure scenarios.'],rubric:['Signal timestamp is point-in-time valid','Fill and markout selection are accounted for','Costs scale with liquidity and order size','Regime and holdout results are visible','No claim is made from synthetic examples alone'],failure:'Displayed imbalance is not a fill, and a historical association does not guarantee a future move. Separate observation, inference, and execution.'},
 {id:'market-maker',title:'Prototype a constrained quoting policy',level:'Advanced · trader / systems',prereq:['10-1','10-2'],brief:'Build a toy simulator for bid/ask quotes, inventory, fills, and adverse-selection markouts. Focus on the state and controls, not profit claims.',steps:['Define event order and quote-update timing.','Implement inventory and gross-exposure constraints.','Simulate fills conditional on a documented order-flow model.','Track spread capture, adverse markout, inventory P&L, and worst-case exposure.','Stress latency, stale market data, and one-sided flow.'],rubric:['Simulator is deterministic under a fixed seed','Fill model assumptions are explicit','Inventory limits work at edge cases','P&L components reconcile','Failure controls are exercised'],failure:'A toy fill model is not a market simulator. Do not infer production performance from stylized flow.'}
];

window.ROLE_TRACKS = [
 {id:'research-architect',title:'Quant researcher & systems architect',tag:'RESEARCH · SYSTEMS · DESIGN',description:'The primary integrated track: bridge careful statistical research, market constraints, maintainable data systems, and clear technical communication.',skills:['Python and tested research code','Data quality, SQL, and time semantics','Probability and statistical reasoning','Portfolio, costs, and microstructure','Reproducible architecture and risk controls'],assess:['algo-hash','sql-join','prob-bayes','stats-leakage','linear-cov','timeseries-split','micro-adverse','systems-repro'],project:'signal-lab',interview:['Design a point-in-time pipeline from market events to a research result. Where can leakage enter?','A promising signal disappears after costs. How would you diagnose the research and execution stack?','How would you design an experiment and its data interfaces so another researcher can reproduce it?']},
 {id:'researcher',title:'Quantitative researcher',tag:'STATISTICS · RESEARCH · EVIDENCE',description:'Develop and defend a testable market hypothesis with sound data, inference, and validation.',skills:['Probability and statistical inference','Python and SQL research workflows','Experimental design and multiple testing','Time series and signal evaluation','Research memo and reproducibility'],assess:['prob-base-rate','stats-testing','stats-leakage','timeseries-split','sql-window'],project:'signal-lab',interview:['Explain a false-discovery problem in a strategy search.','Design a time-aware validation plan for a predictive signal.','Interpret an unstable estimate without overclaiming.']},
 {id:'trader',title:'Quantitative trader',tag:'PROBABILITY · EXECUTION · DECISIONS',description:'Reason quickly about uncertainty, prices, execution, inventory, and market-making tradeoffs.',skills:['Conditional probability and expected value','Market microstructure and order-book behavior','Execution cost and adverse-selection analysis','Risk, inventory, and scenario controls','Timed decision practice and clear communication'],assess:['prob-base-rate','prob-expectation','micro-spread','micro-adverse','linear-dot'],project:'market-maker',interview:['Estimate an expected value and identify a missing assumption.','How does queue position change a passive order decision?','Respond to an unexpected inventory and stale-feed scenario.']},
 {id:'engineer',title:'Quantitative software engineer',tag:'ALGORITHMS · SYSTEMS · DATA',description:'Build correct, observable, and reliable systems around research and trading workflows.',skills:['Algorithms and data structures','Python and SQL code quality','Data modeling and event-time semantics','Testing, profiling, and reproducibility','Failure controls and operational safety'],assess:['algo-search','algo-hash','sql-join','systems-tests','systems-repro'],project:'clean-data',interview:['Explain an algorithm’s time and space complexity.','How do you guard against duplicate or delayed market events?','Design a test strategy for a time-aware feature pipeline.']}
];

window.QUANT_LIBRARY = [
 {title:'Advances in Financial Machine Learning',file:'Advances in Financial Machine Learning.pdf',author:'Marcos López de Prado',use:'Production-chain perspective; data structures; labeling; financial cross-validation; backtest risk; microstructure; high-performance computing.',chapters:['Ch. 2 · Financial data structures','Ch. 3–5 · Labeling, sample weights, stationarity','Ch. 7 · Cross-validation in finance','Ch. 11–14 · Backtest dangers, validation, statistics','Ch. 16 · Asset allocation','Ch. 19 · Microstructural features','Ch. 20–22 · Vectorization, compute, and systems']},
 {title:'Active Portfolio Management',file:'Active Portfolio Management_ A Quantitative Approach for Producing Superior Returns and Controlling Risk.pdf',author:'Richard C. Grinold and Ronald N. Kahn',use:'Risk, forecasts, portfolio construction, turnover, transactions costs, and performance analysis.',chapters:['Ch. 3 · Risk','Ch. 5–6 · Information ratio and breadth','Ch. 10–13 · Forecasting and information horizon','Ch. 14 · Portfolio construction','Ch. 16 · Transactions costs, turnover, and trading','Ch. 17 · Performance analysis']},
 {title:'Trading and Exchanges: Market Microstructure for Practitioners',file:'Trading and exchanges.pdf',author:'Larry Harris',use:'Order properties, trading institutions, dealers, liquidity, volatility, cost measurement, performance, and automated systems.',chapters:['Ch. 4–6 · Orders and order-driven markets','Ch. 13–14 · Dealers and bid/ask spreads','Ch. 19–22 · Liquidity, volatility, transaction costs, performance']},
 {title:'Algorithmic Trading and DMA',file:'Algorithmic Trading and DMA_ An introduction to direct access trading strategies.pdf',author:'Barry Johnson',use:'Direct access, execution decisions, electronic market behavior, and implementation context. Read alongside the market-microstructure modules.'},
 {title:'Quantitative Trading',file:'Quantitative Trading_ How to Build Your Own Algorithmic Trading Business (Wiley Trading).pdf',author:'Ernest P. Chan',use:'Strategy design, backtesting pitfalls, transaction costs, and practical research iteration.',chapters:['Ch. 3 · Backtesting','Backtesting pitfalls and transaction costs sections']},
 {title:'The Three Types of Backtests',file:'three+types+of+backtests.pdf',author:'PDF supplied in the quant folder; author metadata was not reliably extractable',use:'Compare walk-forward, resampling, and Monte Carlo perspectives; discuss survivorship, look-ahead, and transaction-cost risks.'},
 {title:'The Elements of Statistical Learning',file:'The Elements of  Statistical Learning_  Data Mining, Inference, and Prediction..pdf',author:'Trevor Hastie, Robert Tibshirani, and Jerome Friedman',use:'Statistical decision theory, regression, model selection, regularization, and prediction foundations.',chapters:['Ch. 2 · Overview of supervised learning','Ch. 3 · Linear methods for regression','Ch. 7–8 · Model assessment and model selection','Ch. 18 · High-dimensional problems']},
 {title:'Options, Futures, and Other Derivatives',file:'Options, Futures, and Other Derivatives.pdf',author:'John C. Hull',use:'Market instruments, payoff mechanics, hedging, futures, options, and derivatives foundations. Use selectively for asset-specific context.'},
 {title:'Options, Futures, and Other Derivatives · Solutions Manual',file:'Options, Futures, and Other Derivatives - Solutions Manual.pdf',author:'Companion to John C. Hull’s textbook',use:'Use only after attempting a matching textbook problem independently: compare your derivation, locate an arithmetic or assumption error, and then explain the answer without the manual. This is not a source for copying solutions into submissions.'},
 {title:'Financial Data Science with Python',file:'Financial Data Science with Python_ An Integrated Approach To Analysis Modeling And Machine Learning.epub',author:'EPUB in the supplied quant folder',use:'Python-centered applied finance reading. Chapters should be selected in the reader’s EPUB table of contents; the web app does not redistribute the book.'},
 {title:'Inside the Black Box',file:'Inside the Black Box_ A Simple Guide to Systematic Investing (Wiley Finance).pdf',author:'Rishi K. Narang',use:'Systematic research workflow, data, risk, transaction costs, portfolio construction, implementation, and model risk.',chapters:['Ch. 5 · Transaction costs','Ch. 6–7 · Portfolio construction and execution','Ch. 8 · Data','Ch. 9 · Research design','Ch. 10 · Model risk']},
 {title:'MATLAB for Machine Learning',file:'MATLAB for Machine Learning - Second Edition_ Unlock the power of deep learning for swift and enhanced results.pdf',author:'Second edition',use:'Optional comparative machine-learning reference; the core coding path uses Python and SQL.'}
];

window.CURRICULUM_READINGS = {
 0:['Financial Data Science with Python · use the EPUB table of contents for introductory Python/data work.','Inside the Black Box · Ch. 8, data foundations; Ch. 9, scientific research process.'],
 1:['Financial Data Science with Python · Python-oriented analysis reference.','Inside the Black Box · Ch. 8, data quality and storage.'],
 2:['The supplied collection has no dedicated algorithms/data-structures textbook; pair this module with repeated coding drills.'],
 3:['Financial Data Science with Python · Python-first applied reference.','Advances in Financial Machine Learning · Ch. 20, vectorization and computation.'],
 4:['The supplied collection has no dedicated SQL book. Use the query drills and schema/cardinality checklists in this path.','Inside the Black Box · Ch. 8 provides market-data organization context.'],
 5:['Options, Futures, and Other Derivatives · instrument/payoff chapters as optional probability-tree practice.','The Elements of Statistical Learning · Ch. 2.4, statistical decision theory.'],
 6:['The Elements of Statistical Learning · Ch. 2–3, decision theory and linear models; later chapters for model assessment/selection.','Advances in Financial Machine Learning · Ch. 7, financial cross-validation; Ch. 11–14, backtest risks and statistics.'],
 7:['Active Portfolio Management · Ch. 3, risk; Ch. 14, portfolio construction.','Advances in Financial Machine Learning · Ch. 16, asset allocation and optimization risk.'],
 8:['Advances in Financial Machine Learning · Ch. 5, stationarity and memory; Ch. 17, structural breaks.','The Three Types of Backtests · time-aware evaluation and resampling perspectives.'],
 9:['Trading and Exchanges · Ch. 4–6, 13–14, 19–22.','Advances in Financial Machine Learning · Ch. 19, microstructural features.','Algorithmic Trading and DMA · execution/implementation reference.'],
 10:['Quantitative Trading · Ch. 3, backtesting and practical sections on data and costs.','The Three Types of Backtests · compare validation approaches and common sources of bias.'],
 11:['Inside the Black Box · Ch. 9, research and testing; Ch. 10, model and regime risk.','Quantitative Trading · transaction-cost and backtest-pitfall sections.'],
 12:['Advances in Financial Machine Learning · Ch. 20–22, computation and high-performance research.','Inside the Black Box · Ch. 7–8, trading infrastructure and data; Ch. 10, model risk.']
};

/* Lesson-side references pair reading with concrete research techniques. Links point to publisher, DOI, or author-hosted records. */
window.CURRICULUM_REFERENCES = {
 0:{technique:'Write a falsifiable question, predeclare the outcome and record each transformation in a reproducible notebook.',items:[['Python Tutorial · data structures and control flow','https://docs.python.org/3/tutorial/'],['Inside the Black Box · research process and data','https://www.wiley.com/en-us/Inside+the+Black+Box%3A+A+Simple+Guide+to+Systematic+Investing-p-9781119205000']]},
 1:{technique:'Profile raw data first: schema, grain, missingness, duplicates, timestamp, units and point-in-time availability.',items:[['Financial Data Science with Python · applied data workflow','https://www.wiley.com/en-us/Financial+Data+Science+with+Python-p-9781119602985'],['Inside the Black Box · Ch. 8: Data','https://www.wiley.com/en-us/Inside+the+Black+Box%3A+A+Simple+Guide+to+Systematic+Investing-p-9781119205000']]},
 2:{technique:'State the invariant, input constraints, time complexity and space complexity before optimizing.',items:[['Introduction to Algorithms · Cormen, Leiserson, Rivest & Stein','https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/']]},
 3:{technique:'Use small functions with contracts; test boundaries and preserve a reproducible environment and versioned inputs.',items:[['Python Tutorial · errors, functions and modules','https://docs.python.org/3/tutorial/'],['Effective Python · Brett Slatkin','https://effectivepython.com/']]},
 4:{technique:'Declare table grain and key; check uniqueness and row counts before/after joins; use point-in-time as-of joins.',items:[['SQLite SELECT reference · joins and window functions','https://www.sqlite.org/lang_select.html'],['Use The Index, Luke! · SQL performance and indexing','https://use-the-index-luke.com/']]},
 5:{technique:'Draw a probability tree; distinguish P(A|B) from P(B|A); compute expected value and downside before acting.',items:[['Introduction to Probability · Blitzstein & Hwang','https://projects.iq.harvard.edu/stat110/home']]},
 6:{technique:'Preserve an untouched holdout, log every trial, and account for dependence, selection and non-normal tails.',items:[['A Reality Check for Data Snooping · Halbert White (2000)','https://doi.org/10.1111/1468-0262.00152'],['The Deflated Sharpe Ratio · Bailey & López de Prado (2014)','https://doi.org/10.2139/ssrn.2460551'],['The Elements of Statistical Learning · Ch. 7–8: assessment and model selection','https://hastie.su.domains/ElemStatLearn/']]},
 7:{technique:'Separate forecast quality from portfolio construction; impose risk, turnover and cost constraints explicitly.',items:[['Active Portfolio Management · Grinold & Kahn','https://www.mheducation.com/highered/product/active-portfolio-management-grinold-kahn/M9780070248823.html'],['Convex Optimization · Boyd & Vandenberghe','https://web.stanford.edu/~boyd/cvxbook/']]},
 8:{technique:'Use rolling-origin evaluation, inspect stationarity and regime changes, and avoid random shuffles for time series.',items:[['Time Series Analysis · James D. Hamilton','https://press.princeton.edu/books/hardcover/9780691042893/time-series-analysis'],['Forecasting: Principles and Practice · rolling-origin validation','https://otexts.com/fpp3/tscv.html']]},
 9:{technique:'Model spread, queue position, adverse selection and impact; distinguish displayed liquidity from executable fills.',items:[['Trading and Exchanges · Larry Harris','https://global.oup.com/academic/product/trading-and-exchanges-9780195144703'],['Continuous Auctions and Insider Trading · Albert S. Kyle (1985)','https://doi.org/10.2307/1913210'],['Bid, Ask and Transaction Prices in a Specialist Market · Glosten & Milgrom (1985)','https://doi.org/10.1016/0304-405X(85)90044-3']]},
 10:{technique:'Freeze hypotheses before evaluation; use walk-forward splits, realistic fills and a ledger of all variants tried.',items:[['The Deflated Sharpe Ratio · Bailey & López de Prado (2014)','https://doi.org/10.2139/ssrn.2460551'],['A Reality Check for Data Snooping · Halbert White (2000)','https://doi.org/10.1111/1468-0262.00152'],['Advances in Financial Machine Learning · Ch. 7 and 11–14','https://www.wiley.com/en-us/Advances+in+Financial+Machine+Learning-p-9781119482086']]},
 11:{technique:'Write an experiment card, preserve a negative-results log and rerun the analysis from a clean environment.',items:[['Inside the Black Box · Ch. 9–10: research and model risk','https://www.wiley.com/en-us/Inside+the+Black+Box%3A+A+Simple+Guide+to+Systematic+Investing-p-9781119205000'],['The Three Types of Backtests · supplied reading in your quant folder',''] ]},
 12:{technique:'Design explicit data contracts, idempotent event handling, observability, replayable inputs and fail-safe behavior.',items:[['Designing Data-Intensive Applications · Martin Kleppmann','https://dataintensive.net/'],['Advances in Financial Machine Learning · Ch. 20–22: computation and systems','https://www.wiley.com/en-us/Advances+in+Financial+Machine+Learning-p-9781119482086']]}
};

window.CODING_EXERCISES = {
 python:[
  {name:'4 · Find the first duplicate',prompt:'LEVEL 02 / ALGORITHMS · SET MEMBERSHIP',brief:'Use a set to detect repeated keys in one pass.',body:'Implement first_duplicate(values). Return the first value encountered that has already appeared, or None if every value is unique.',code:'def first_duplicate(values):\n    # Return the first repeated value, or None\n    pass',testCode:'_cases = [(["A", "B", "A", "C"], "A"), ([4, 1, 3, 2], None), ([9, 8, 9, 8], 9)]\nfor _values, _expected in _cases:\n    assert first_duplicate(_values) == _expected, f"input={_values}"\nprint("ALL 3 TEST CASES PASSED")',test:(out)=>({ok:out.includes('ALL 3 TEST CASES PASSED'),label:'All 3 visible-contract / hidden-example cases passed.'})},
  {name:'5 · Calculate rolling means',prompt:'LEVEL 02 / ARRAYS · WINDOW SEMANTICS',brief:'Build an inclusive trailing window and preserve its alignment.',body:'Implement rolling_mean(values, window). Return the mean for each complete trailing window. For [1, 2, 3, 4] with window 3, return [2, 3]. Raise ValueError if window is not positive.',code:'def rolling_mean(values, window):\n    # Return one mean for every complete trailing window\n    pass',testCode:'_cases = [([1,2,3,4], 3, [2.0,3.0]), ([10], 1, [10.0]), ([1,2,3], 4, [])]\nfor _v, _w, _want in _cases:\n    _got = rolling_mean(_v, _w)\n    assert len(_got) == len(_want) and all(abs(a-b)<1e-9 for a,b in zip(_got,_want)), f"input={_v}, window={_w}, got={_got}"\ntry:\n    rolling_mean([1,2], 0)\n    raise AssertionError("window=0 must fail")\nexcept ValueError:\n    pass\nprint("ALL 4 TEST CASES PASSED")',test:(out)=>({ok:out.includes('ALL 4 TEST CASES PASSED'),label:'Three value cases and the invalid-window case passed.'})},
  {name:'6 · Compute maximum drawdown',prompt:'LEVEL 03 / RISK · PATH DEPENDENCE',brief:'Drawdown depends on the path and prior peak, not only on total return.',body:'Implement max_drawdown(returns) using simple returns. Wealth starts at 1.0. Return the largest peak-to-trough fractional loss as a positive number; reject returns less than or equal to −1.',code:'def max_drawdown(returns):\n    # Track wealth and its running peak\n    pass',testCode:'_cases = [([0.10,-0.10], 0.10), ([0.0,0.0], 0.0), ([-0.20,0.25,-0.10], 0.20)]\nfor _r, _want in _cases:\n    _got = max_drawdown(_r)\n    assert abs(_got-_want)<1e-9, f"returns={_r}, got={_got}, wanted={_want}"\ntry:\n    max_drawdown([-1.0])\n    raise AssertionError("return <= -100% must fail")\nexcept ValueError:\n    pass\nprint("ALL 4 TEST CASES PASSED")',test:(out)=>({ok:out.includes('ALL 4 TEST CASES PASSED'),label:'Path, recovery, and impossible-return edge cases passed.'})},
  {name:'7 · Apply a fill to inventory',prompt:'LEVEL 03 / TRADING · POSITION STATE',brief:'Make sign conventions and invariants explicit in order-state logic.',body:'Implement apply_fill(inventory, side, quantity). A buy increases inventory, a sell decreases it. Reject a negative quantity and any side other than “buy” or “sell”.',code:'def apply_fill(inventory, side, quantity):\n    # Return updated signed inventory\n    pass',testCode:'assert apply_fill(0, "buy", 7) == 7\nassert apply_fill(7, "sell", 10) == -3\nassert apply_fill(-2, "buy", 0) == -2\nfor _side, _qty in [("buy",-1),("hold",2)]:\n    try:\n        apply_fill(0, _side, _qty)\n        raise AssertionError("invalid fill must fail")\n    except ValueError:\n        pass\nprint("ALL 5 TEST CASES PASSED")',test:(out)=>({ok:out.includes('ALL 5 TEST CASES PASSED'),label:'Sign convention, zero fill, and invalid input cases passed.'})},
  {name:'8 · Net return after costs',prompt:'LEVEL 02 / RESEARCH · COST ACCOUNTING',brief:'Handle cost components and units deliberately.',body:'Implement net_bps(gross_bps, spread_bps, fees_bps, impact_bps). Return gross less all costs; reject negative costs. Inputs are all basis points.',code:'def net_bps(gross_bps, spread_bps, fees_bps, impact_bps):\n    pass',testCode:'assert net_bps(18,6,1,3) == 8\nassert net_bps(0,0,0,0) == 0\nassert net_bps(-2,1,0,0) == -3\ntry:\n    net_bps(10,-1,0,0)\n    raise AssertionError("negative cost must fail")\nexcept ValueError:\n    pass\nprint("ALL 4 TEST CASES PASSED")',test:(out)=>({ok:out.includes('ALL 4 TEST CASES PASSED'),label:'Ordinary, zero, negative-gross, and invalid-cost cases passed.'})},
  {name:'9 · Score a prediction stream',prompt:'LEVEL 03 / STATISTICS · CLASSIFICATION METRICS',brief:'Implement a simple classification metric and handle empty samples.',body:'Implement accuracy(actual, predicted). Raise ValueError if lengths differ or both are empty. Return the fraction of equal labels.',code:'def accuracy(actual, predicted):\n    pass',testCode:'assert accuracy([1,0,1,1], [1,1,1,0]) == 0.5\nassert accuracy(["up"], ["up"]) == 1.0\nassert accuracy([0,1], [1,0]) == 0.0\nfor _a,_p in [([],[]),([1],[1,0])]:\n    try:\n        accuracy(_a,_p)\n        raise AssertionError("invalid lengths must fail")\n    except ValueError:\n        pass\nprint("ALL 5 TEST CASES PASSED")',test:(out)=>({ok:out.includes('ALL 5 TEST CASES PASSED'),label:'Balanced, single-row, reversed, and invalid samples passed.'})}
 ],
 sql:[
  {name:'4 · Add an explicit risk flag',prompt:'LEVEL 02 / SQL · CASE EXPRESSIONS',brief:'Classify rows with a transparent rule that can be reviewed.',body:'Use CASE to label each row as ACTIVE when volume exceeds 1,500,000 and QUIET otherwise. Return symbol and label.',code:'SELECT symbol,\n       CASE WHEN volume > 1500000 THEN \'ACTIVE\' ELSE \'QUIET\' END AS activity\nFROM daily_prices\nORDER BY symbol, date;',test:(out)=>({ok:out.includes('activity')&&out.includes('ACTIVE')&&out.includes('QUIET'),label:'Both explicit categories appear in the result.'})},
  {name:'5 · Compute a point-in-time return',prompt:'LEVEL 03 / SQL · LAG AND ORDER',brief:'Compute adjacent close-to-close returns within each symbol.',body:'Use LAG(close) partitioned by symbol and ordered by date. The first observation per symbol should have no prior close.',code:'SELECT symbol, date, close,\n       close / LAG(close) OVER (PARTITION BY symbol ORDER BY date) - 1 AS return_1d\nFROM daily_prices\nORDER BY symbol, date;',test:(out)=>({ok:out.includes('return_1d')&&out.includes('ALFA')&&out.includes('NULL'),label:'Per-symbol lagged returns returned with a NULL first observation.'})},
  {name:'6 · Expose row-count differences',prompt:'LEVEL 02 / SQL · DATA DIAGNOSTICS',brief:'Compare row counts with distinct dates to expose duplicate symbol/date keys.',body:'Return total rows and distinct symbol/date pairs per symbol. A difference indicates duplicate keys that should be explained.',code:'SELECT symbol, COUNT(*) AS rows_total,\n       COUNT(DISTINCT date) AS unique_dates\nFROM daily_prices\nGROUP BY symbol\nORDER BY symbol;',test:(out)=>({ok:out.includes('rows_total')&&out.includes('unique_dates')&&out.includes('ALFA'),label:'Total and distinct-date counts returned per symbol.'})},
  {name:'7 · Inspect daily price ranges',prompt:'LEVEL 02 / SQL · GROUPED DIAGNOSTICS',brief:'Summarize within each symbol before considering model features.',body:'Return each symbol’s minimum and maximum close and row count, ordered by symbol.',code:'SELECT symbol, MIN(close) AS min_close, MAX(close) AS max_close,\n       COUNT(*) AS observations\nFROM daily_prices\nGROUP BY symbol\nORDER BY symbol;',test:(out)=>({ok:out.includes('min_close')&&out.includes('max_close')&&out.includes('observations'),label:'Grouped ranges and sample sizes returned.'})}
 ]
};
